### ISSUE TITLE
Overflow on mobile

### ISSUE THREAD

**Issue by rabbishuki** [RusinovAnton/js-tldr#108]
Amazing idea,

Just checked it on my phone, and the text flows out of its box.

![Screenshot_20191127-194139](https://user-images.githubusercontent.com/24904197/69746897-f93e8700-114d-11ea-960d-15f355faf9ac.png)

**Comment by RusinovAnton** [comment]
Thank you. Going to handle it asap!

**Comment by RusinovAnton** [comment]
fixed version is live now

**Comment by rabbishuki** [comment]
Wow you are quick!
