### ISSUE TITLE
Website seems to be down

### ISSUE THREAD

**Issue by Gilstroem** [RusinovAnton/js-tldr#144]
Hey @RusinovAnton , the website seems to be down 😬

**On https:** it fails completely

**On http:**
<img width="1440" alt="Screenshot 2020-01-16 at 19 25 56" src="https://user-images.githubusercontent.com/16057281/72556196-08ac9780-3896-11ea-9330-5724dcee51a1.png">

**Comment by RusinovAnton** [comment]
Thanks for taking the time to report this. I ran out of credit in GCP and found it too expensive. Now figuring out the certificates at digitalocean.

**Comment by Gilstroem** [comment]
That is totally fair, just a heads-up 

Have you considered hosting it for free on something like Netlify? Apart from the "liking/helpful" functionality, it seems like a perfectly static use case 😊

**Comment by RusinovAnton** [comment]
Oh, that's brilliant advice. Somehow I heard of Netlify but never tried it before. I like the way it provides continuous delivery out of the box for free. Meanwhile, the site should be up and running by this time, but I'll try to test Netlify further and migrate. Thanks again
