### ISSUE TITLE
Math methods

### ISSUE THREAD

**Issue by RusinovAnton** [RusinovAnton/js-tldr#15]

**Comment by Bikossor** [comment]
Can I help you out with that?

**Comment by RusinovAnton** [comment]
@Bikossor please do, that'd be terrific

**Comment by RusinovAnton** [comment]
- You can find the empty files for Math methods/properties at the `public/docs/Math` directory here: 
https://github.com/RusinovAnton/js-tldr/tree/master/public/docs/Math
- To add them to search index, you'll need to create a hash in the `index.json` here:
https://github.com/RusinovAnton/js-tldr/blob/master/public/docs/index.json
- I've added some basic contribution guide here: 
https://github.com/RusinovAnton/js-tldr#contribution-guide

**Comment by Bikossor** [comment]
@RusinovAnton Thank you! Could you assign the issue to me?

**Comment by RusinovAnton** [comment]
Hey @Bikossor, what's the status of this one? Do you need any help?

**Comment by Bikossor** [comment]
@RusinovAnton I'm half way through. I'll be finishing this today :)

**Comment by Bikossor** [comment]
@RusinovAnton Done 😄
